title: Sercan GEZER
author: Sercan GEZER
email: sercangezer.tr@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Linux sistem yönetimi üzerine uzmanlaşmak isteyip JD Edwards EnterpriseOne ve Weblogic ile boğuşan bir şahıs
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/sayfa-:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: sercangezer

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://www.linkedin.com/in/sercangezer/
      icon: linkedin
      color: cyan

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
