site: Sercan GEZER | Linux/DevOps Sistem Mühendisi 🇹🇷
title: Sercan GEZER | Linux/DevOps Sistem Mühendisi 🇹🇷
greetings: Sercan GEZER 🇹🇷
description: >-
  Linux/DevOps konularında Türk Bilişim topluluğuna küçük bir katkı amacıyla oluşturulmuş bir blog.
lang: tr-TR
timezone:  Europe/Istanbul
repo: https://github.com/sercangezer/sercangezer.github.io # site repo [optional]
data-theme: "light" # default theme "dark" | "light"
discus-identifier: sercangezer # replace with your disqus shortname

author:
  name: Sercan GEZER
  bio: Linux/DevOps Sistem Mühendisi 
  userpicture: 
  username: Sercan GEZER
  github: sercangezer
  twitter: # twitter username
  email: sercan.gezer.tr@gmail.com

# Font Settings
googlewebfonts: family=Victor+Mono:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://www.sercangezer.com.tr" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 

# RSS
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


