# Site settings
title_left    : "Sercan GEZER"
title_right   : "   #Linux" # default: ""
description   : "Linux terminale dair bir şeyler."
keywords      : "linux, bash, ubuntu, debian, unix, terminal, shell, xterm, command line, script"
url           : https://sercangezer.github.io # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : G-JV6L09S1HJ
twitter_username  : ""
comments_enabled  : true # if enabled (set to true), please provide your disqus_username
disqus_shortname  : "sercangezer"
postshare_enabled : true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Sercan GEZER"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: Hakkımda
  - slug : blog
    title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
