apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
spec:
  selector: 
    app: nexus
  type: NodePort  
  ports:
    - name: nexus-web-ui
      port: 8081
      targetPort: 8081
      nodePort: 30880